format = "[󰇥](yellow) $directory $git_branch\n$character"

[directory]
format = "[ $path]($style)"
truncate_to_repo = false
style = "blue"

[git_branch]
format = "[ $branch]($style)"
style = "green"

[character]
format = "[$symbol](white) "
success_symbol = "\\$"
error_symbol = "\\$"
