local colors = {
	-- Colors
	midnight = "#19191f",
	cream = "#e9e7dd",
	hibiscus = "#ff007b",
	red = "#e61919",
	orange = "#e68019",
	green = "#14b814",

	-- Shade ramp
	grey20 = "#333333",
	grey30 = "#4d4d4d",
	grey60 = "#999999",
	grey70 = "#b3b3b3",
	grey80 = "#cccccc",
	grey90 = "#e6e6e6",
}

local theme = {
	dark = {
		bg = colors.midnight,
		bg_plus = colors.grey20,
		bg_plus_plus = colors.grey30,
		mg = colors.grey60,
		fg_minus_minus = colors.grey70,
		fg_minus = colors.grey80,
		fg = colors.grey90,
		cursor_bg = colors.hibiscus,
		error = colors.red,
		warning = colors.orange,
		success = colors.green,
		higlights = {},
	},
	light = {
		bg = "",
		bg_plus = "",
		bg_plus_plus = "",
		mg = "",
		fg_minus_minus = "",
		fg_minus = "",
		fg = "",
		cursor_bg = "",
		cursor_fg = "",
		error = "",
		warning = "",
		success = "",
		higlights = {},
	},
}
-- build/pax_zero.lua

local colors = {
	-- content here will not be touched
	-- PATCH_OPEN
	Normal = { fg = "#e6e6e6", bg = "#1a1a1a" },
	Error = { link = "Normal" },
	FloatTitle = { link = "Normal" },
	Ignore = { link = "Normal" },
	LspCodeLens = { link = "Normal" },
	LspCodeLensSeparator = { link = "Normal" },
	LspReferenceRead = { link = "Normal" },
	LspReferenceText = { link = "Normal" },
	LspReferenceWrite = { link = "Normal" },
	LspSignatureActiveParameter = { link = "Normal" },
	ModeMsg = { link = "Normal" },
	NormalFloat = { link = "Normal" },
	NormalNC = { link = "Normal" },
	SpecialKey = { link = "Normal" },
	SpellBad = { link = "Normal" },
	SpellCap = { link = "Normal" },
	SpellLocal = { link = "Normal" },
	SpellRare = { link = "Normal" },
	StatusLine = { link = "Normal" },
	Title = { link = "Normal" },
	Todo = { link = "Normal" },
	VertSplit = { link = "Normal" },
	Whitespace = { link = "Normal" },
	ColorColumn = { bg = "#333333" },
	Comment = { fg = "#999999", italic = true },
	Conceal = { fg = "#1a1a1a", bg = "#1a1a1a" },
	Constant = { fg = "#e6e6e6" },
	["@none.javascript"] = { link = "Constant" },
	["@none.tsx"] = { link = "Constant" },
	CurSearch = { fg = "#e6e6e6", bg = "#1a1a1a", reverse = true },
	Substitute = { link = "CurSearch" },
	Cursor = { fg = "#e6e6e6", bg = "#ff007b" },
	CursorIM = { link = "Cursor" },
	lCursor = { link = "Cursor" },
	CursorLine = { bg = "#4d4d4d" },
	CursorColumn = { link = "CursorLine" },
	CursorLineFold = { link = "CursorLine" },
	CursorLineSign = { link = "CursorLine" },
	CursorLineNr = { fg = "#e6e6e6", bg = "#4d4d4d" },
	CustomRulerError = { fg = "#e61919", bg = "#1a1a1a" },
	CustomRulerIcon = { fg = "#e6e6e6", bg = "#1a1a1a", reverse = true },
	Delimiter = { fg = "#e6e6e6" },
	["@constructor.lua"] = { link = "Delimiter" },
	DiagnosticError = { fg = "#e61919" },
	DiagnosticHint = { fg = "#999999" },
	DiagnosticInfo = { fg = "#999999" },
	DiagnosticOk = { fg = "#999999" },
	DiagnosticUnderlineError = { fg = "#e61919", underline = true },
	DiagnosticUnderlineWarn = { fg = "#e68019", underline = true },
	DiagnosticUnnecessary = { italic = true, underline = true },
	DiagnosticWarn = { fg = "#e68019" },
	DiffAdd = {},
	DiffChange = {},
	DiffDelete = {},
	DiffText = {},
	Directory = { fg = "#e6e6e6" },
	EndOfBuffer = { fg = "#1a1a1a", bg = "#1a1a1a" },
	ErrorMsg = { fg = "#e61919" },
	FloatBorder = { fg = "#e6e6e6" },
	FoldColumn = {},
	Folded = {},
	Function = { fg = "#b3b3b3" },
	["@constructor.javascript"] = { link = "Function" },
	["@constructor.tsx"] = { link = "Function" },
	["@constructor.typescript"] = { link = "Function" },
	Identifier = { fg = "#e6e6e6" },
	IncSearch = { fg = "#e6e6e6", bg = "#1a1a1a", reverse = true },
	Search = { link = "IncSearch" },
	LineNr = { fg = "#999999" },
	LineNrAbove = { link = "LineNr" },
	LineNrBelow = { link = "LineNr" },
	MatchParen = { fg = "#e6e6e6", bg = "#1a1a1a", reverse = true },
	CustomRulerFile = { link = "ModeMsg" },
	CustomRulerSeparator = { link = "ModeMsg" },
	MoreMsg = { link = "ModeMsg" },
	MsgArea = { link = "ModeMsg" },
	MsgSeparator = { link = "ModeMsg" },
	Question = { link = "ModeMsg" },
	NonText = {},
	Pmenu = { fg = "#cccccc", bg = "#333333" },
	PmenuExtra = { link = "Pmenu" },
	PmenuKind = { link = "Pmenu" },
	PmenuSbar = { bg = "#333333" },
	PmenuSel = { fg = "#cccccc", bg = "#333333", reverse = true },
	PmenuExtraSel = { link = "PmenuSel" },
	PmenuKindSel = { link = "PmenuSel" },
	QuickFixLine = { link = "PmenuSel" },
	WildMenu = { link = "PmenuSel" },
	PmenuThumb = { bg = "#cccccc" },
	PreProc = { fg = "#e6e6e6", bold = true },
	SignColumn = {},
	Special = { fg = "#e6e6e6" },
	Statement = { fg = "#e6e6e6", bold = true },
	["@function.builtin.javascript"] = { link = "Statement" },
	StatusLineNC = { fg = "#1a1a1a", bg = "#1a1a1a" },
	TabLine = {},
	TabLineFill = {},
	TabLineSel = {},
	TermCursor = { bg = "#ff007b" },
	TermCursorNC = {},
	Type = { fg = "#cccccc" },
	Underlined = { underline = true },
	Visual = { fg = "#4d4d4d", bg = "#b3b3b3" },
	VisualNOS = { link = "Visual" },
	WarningMsg = { fg = "#e68019" },
	WinBar = {},
	WinBarNC = {},
	Winseparator = {},
	["@boolean.javascript"] = { fg = "#cccccc", bold = true },
	["@boolean.lua"] = { fg = "#cccccc", bold = true },
	["@boolean.tsx"] = { fg = "#cccccc", bold = true },
	["@boolean.typescript"] = { fg = "#cccccc", bold = true },
	["@constant.builtin.javascript"] = { fg = "#cccccc", bold = true },
	["@constant.builtin.tsx"] = { fg = "#cccccc", bold = true },
	["@constant.builtin.typescript"] = { fg = "#cccccc", bold = true },
	["@tag.attribute.javascript"] = { fg = "#cccccc", italic = true },
	["@tag.attribute.tsx"] = { fg = "#cccccc", italic = true },
	["@tag.builtin.javascript"] = { fg = "#cccccc", italic = true },
	["@tag.builtin.tsx"] = { fg = "#cccccc", italic = true },
	["@tag.delimiter.javascript"] = { fg = "#e6e6e6", bold = true },
	["@tag.delimiter.tsx"] = { fg = "#e6e6e6", bold = true },
	["@tag.javascript"] = { fg = "#cccccc", italic = true },
	["@tag.tsx"] = { fg = "#cccccc", italic = true },
	-- PATCH_CLOSE
	-- content here will not be touched
}

-- colorschemes generally want to do this
vim.cmd("highlight clear")
vim.cmd("set t_Co=256")
vim.cmd("let g:colors_name='pax_zero'")

-- apply highlight groups
for group, attrs in pairs(colors) do
	vim.api.nvim_set_hl(0, group, attrs)
end
