-- TODO figure out how to move these to be file specific (nb want these ones
-- available for js/jsx/ts/tsx files, not just a single filetype)
--vim.cmd("iab tbitd toBeInTheDocument()<Esc>")
--vim.cmd("iab fna () => {}")
